# --- !Ups

create table "phones" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "number" varchar not null
);

# --- !Downs

drop table "PHONES" if exists;
